log:
  disable_sentry: true
  level: debug

db:
  url: postgres://postgres:postgres@localhost:5432/rarimo_dex_oracle?sslmode=disable

listener:
  addr: :8000

redis:
  addr: localhost:6379
  db: 0

tokens_observer:
  interval: 5s

balances_observer:
  interval: 5s
  page_size: 100

evm:
  rpc: "wss://goerli.infura.io/ws/v3/633a4db0ad9c4684a7067bab4fa6c572"

chains:
  list:
    - id: 56
      name: "BSC"
      rpc_url: "https://bsc-dataseed.binance.org/"
      native_symbol: BNB
      explorer_url: "https://bscscan.com"
      type: 0 # 0 = EVM, 1 = Solana, 2 = Near, 3 = Other
      kind: "mainnet"
      icon_url: "https://raw.githubusercontent.com/MetaMask/metamask-extension/develop/app/images/bnb.png"
      swap_contract_address: "0x85718348D854CE2768e96D87a2ed6d12d619b67B"
      swap_contract_version: "PancakeSwap"
      tokens_info:
        list_urls:
          - "https://tokens.pancakeswap.finance/pancakeswap-extended.json"
          - "https://raw.githubusercontent.com/pancakeswap/token-list/main/lists/cmc.json"
        tokens:
          - address: "0x183A7d78c6d0B8211351954CDEA8c7c00CAE2470"
            name: "FooBar Token"
            symbol: "FOOBAR"
            decimals: 18
            logo_uri: "https://ps.w.org/foobar-notifications-lite/assets/icon-256x256.gif"
