log:
  disable_sentry: true
  level: debug

db:
  url: postgres://postgres:postgres@localhost:5432/rarimo_dex_oracle?sslmode=disable

listener:
  addr: :8000

redis:
  addr: localhost:6379
  db: 0

tokens_observer:
  interval: 5s

balances_observer:
  interval: 5s
  page_size: 100

chains:
  list:
    - id: 1
      name: "Ethereum"
      rpc_url_client: "https://mainnet.infura.io/v3/"
      rpc_url: "https://mainnet.infura.io/v3/<apikey>"
      native_symbol: ETH
      explorer_url: "https://etherscan.io"
      type: 0 # 0 = EVM, 1 = Solana, 2 = Near, 3 = Other
      kind: "mainnet"
      icon_url: "https://raw.githubusercontent.com/rarimo/js-sdk/1.5.0/assets/logos/eth-logo.png" # TODO all this URLs (unused in the service) should be hosted as a static json elsewhere
      fee_manager_address: ""
      swap_contract_address: "0x9b365BF9cF2d73Cb8e6C9ac1f8a740232D61a6A2"
      swap_contract_version: "UniswapV3"
      balance_multigetter_addr: "0x2a7d9123a99fb88c71deb730011a43f3e579ffdd"
      tokens_info:
        tokens:
          - address: "0x0000000000000000000000000000000000000000"
            name: "Ethereum Native Currency"
            symbol: "ETH"
            decimals: 18
            logo_uri: "https://raw.githubusercontent.com/rarimo/js-sdk/1.5.0/assets/logos/eth-logo.png"
            native: true
        list_urls:
          - "https://ipfs.testnet.rarimo.com/ipfs/ipns/tokens.uniswap.org"
          - "https://tokens.coingecko.com/uniswap/all.json"
    - id: 5
      name: "Goerli"
      rpc_url_client: "https://goerli.infura.io/v3/"
      rpc_url: "https://goerli.infura.io/v3/<apikey>"
      native_symbol: ETH
      explorer_url: "https://goerli.etherscan.io"
      type: 0 # 0 = EVM, 1 = Solana, 2 = Near, 3 = Other
      kind: "testnet"
      icon_url: "https://raw.githubusercontent.com/rarimo/js-sdk/1.5.0/assets/logos/eth-logo.png"
      fee_manager_address: ""
      swap_contract_address: "0xa10093a0D0970Fc1De02faF8e1884f414dC05Dbe"
      swap_contract_version: "UniswapV3"
      balance_multigetter_addr: "0xD48A9C5D936A78b7c766d956f9Ff7B541c8aEe7D"
      tokens_info:
        tokens:
          - address: "0x0000000000000000000000000000000000000000"
            name: "Goerli Ethereum"
            symbol: "ETH"
            decimals: 18
            logo_uri: "https://raw.githubusercontent.com/rarimo/js-sdk/1.5.0/assets/logos/eth-logo.png"
            native: true
        list_urls:
          - "https://ipfs.testnet.rarimo.com/ipfs/ipns/tokens.uniswap.org"
    - id: 137
      name: "Polygon"
      rpc_url_client: "https://polygon-rpc.com/"
      rpc_url: "https://polygon-rpc.com/"
      native_symbol: MATIC
      explorer_url: "https://polygonscan.com"
      type: 0 # 0 = EVM, 1 = Solana, 2 = Near, 3 = Other
      kind: "mainnet"
      icon_url: "https://raw.githubusercontent.com/rarimo/js-sdk/1.5.0/assets/logos/matic-logo.png"
      fee_manager_address: ""
      swap_contract_address: "0xa809168D07f6AEE4f0878Bfc5DC931A5612cFeb1"
      swap_contract_version: "QuickSwap"
      balance_multigetter_addr: "0x2a7d9123a99Fb88C71DEb730011a43F3E579FFdd"
      tokens_info:
        tokens:
          - address: "0x0000000000000000000000000000000000000000"
            name: "Polygon Matic"
            symbol: "MATIC"
            decimals: 18
            logo_uri: "https://raw.githubusercontent.com/rarimo/js-sdk/1.5.0/assets/logos/matic-logo.png"
            native: true
        list_urls:
          - "https://unpkg.com/quickswap-default-token-list@1.2.78/build/quickswap-default.tokenlist.json"
    - id: 43114
      name: "Avalanche"
      rpc_url_client: "https://api.avax.network/ext/bc/C/rpc"
      rpc_url: "https://api.avax.network/ext/bc/C/rpc"
      native_symbol: AVAX
      explorer_url: "https://snowtrace.io"
      type: 0 # 0 = EVM, 1 = Solana, 2 = Near, 3 = Other
      kind: "testnet"
      icon_url: "https://raw.githubusercontent.com/rarimo/js-sdk/1.5.0/assets/logos/avax-logo.png"
      fee_manager_address: ""
      swap_contract_address: "0xa809168D07f6AEE4f0878Bfc5DC931A5612cFeb1"
      swap_contract_version: "TraderJoe"
      balance_multigetter_addr: "0x2a7d9123a99Fb88C71DEb730011a43F3E579FFdd"
      tokens_info:
        tokens:
          - address: "0x0000000000000000000000000000000000000000"
            name: "Avalanche"
            symbol: "AVAX"
            decimals: 18
            logo_uri: "https://raw.githubusercontent.com/rarimo/js-sdk/1.5.0/assets/logos/avax-logo.png"
            native: true
        list_urls:
          - "https://raw.githubusercontent.com/traderjoe-xyz/joe-tokenlists/main/mc.tokenlist.json"
    - id: 43113
      name: "fuji"
      rpc_url_client: "https://api.avax-test.network/ext/bc/C/rpc"
      rpc_url: "https://api.avax-test.network/ext/bc/C/rpc"
      native_symbol: AVAX
      explorer_url: "https://testnet.snowtrace.io"
      type: 0 # 0 = EVM, 1 = Solana, 2 = Near, 3 = Other
      kind: "testnet"
      icon_url: "https://raw.githubusercontent.com/rarimo/js-sdk/1.5.0/assets/logos/avax-logo.png"
      fee_manager_address: ""
      swap_contract_address: "0xad3C3F305FDcA1f2028d63000453a25ffFF4e289"
      swap_contract_version: "TraderJoe"
      balance_multigetter_addr: "0x2a7d9123a99fb88c71deb730011a43f3e579ffdd"
      tokens_info:
        tokens:
          - address: "0x0000000000000000000000000000000000000000"
            name: "Fuji Avalanche"
            symbol: "AVAX"
            decimals: 18
            logo_uri: "https://raw.githubusercontent.com/rarimo/js-sdk/1.5.0/assets/logos/avax-logo.png"
            native: true
          - address: "0xd00ae08403B9bbb9124bB305C09058E32C39A48c"
            name: "Wrapped AVAX"
            symbol: "WAVAX"
            decimals: 18
            logo_uri: "https://raw.githubusercontent.com/traderjoe-xyz/joe-tokenlists/main/logos/0xd00ae08403B9bbb9124bB305C09058E32C39A48c/logo.png"
          - address: "0xB6076C93701D6a07266c31066B298AeC6dd65c2d"
            name: "USD Coin"
            symbol: "USDC"
            decimals: 6
            logo_uri: "https://raw.githubusercontent.com/traderjoe-xyz/joe-tokenlists/main/logos/0xB6076C93701D6a07266c31066B298AeC6dd65c2d/logo.png"
    - id: 56
      name: "BSC"
      rpc_url_client: "https://bsc-dataseed.binance.org/"
      rpc_url: "https://bsc-dataseed.binance.org/"
      native_symbol: BNB
      explorer_url: "https://bscscan.com"
      type: 0 # 0 = EVM, 1 = Solana, 2 = Near, 3 = Other
      kind: "mainnet"
      icon_url: "https://raw.githubusercontent.com/rarimo/js-sdk/1.5.0/assets/logos/bnb-logo.png"
      fee_manager_address: ""
      swap_contract_address: "0x1C4bc89d32bB4Ec19F9B54Ae457F249C2B133851"
      swap_contract_version: "PancakeSwap"
      balance_multigetter_addr: "0x2a7d9123a99Fb88C71DEb730011a43F3E579FFdd"
      tokens_info:
        tokens:
          - address: "0x0000000000000000000000000000000000000000"
            name: "Binance Coin"
            symbol: "BNB"
            decimals: 18
            logo_uri: "https://raw.githubusercontent.com/rarimo/js-sdk/1.5.0/assets/logos/bnb-logo.png"
            native: true
        list_urls:
          - "https://tokens.pancakeswap.finance/pancakeswap-extended.json"
          - "https://raw.githubusercontent.com/pancakeswap/token-list/main/lists/cmc.json"
    - id: 97
      name: "Binance Smart Chain Testnet"
      rpc_url_client: "https://data-seed-prebsc-1-s1.binance.org:8545/"
      rpc_url: "https://data-seed-prebsc-1-s1.binance.org:8545/"
      native_symbol: tBNB
      explorer_url: "https://testnet.bscscan.com"
      type: 0 # 0 = EVM, 1 = Solana, 2 = Near, 3 = Other
      kind: "testnet"
      icon_url: "https://raw.githubusercontent.com/rarimo/js-sdk/1.5.0/assets/logos/bnb-logo.png"
      fee_manager_address: ""
      swap_contract_address: "0xcb62bBC9F6360276B2e326F27023e565D638967A"
      swap_contract_version: "PancakeSwap"
      balance_multigetter_addr: "0x2a7d9123a99fb88c71deb730011a43f3e579ffdd"
      tokens_info:
        tokens:
          - address: "0x0000000000000000000000000000000000000000"
            name: "Binance Testnet Coin"
            symbol: "tBNB"
            decimals: 18
            logo_uri: "https://raw.githubusercontent.com/rarimo/js-sdk/1.5.0/assets/logos/bnb-logo.png"
            native: true
          - address: "0x8BaBbB98678facC7342735486C851ABD7A0d17Ca"
            name: "Ethereum Token"
            symbol: "ETH"
            decimals: 18
            logo_uri: "https://raw.githubusercontent.com/rarimo/js-sdk/1.5.0/assets/logos/eth-logo.png"
          - address: "0xae13d989dac2f0debff460ac112a837c89baa7cd"
            name: "Wrapped Binance Testnet Token"
            symbol: "WBNB"
            decimals: 18
            logo_uri: "https://raw.githubusercontent.com/rarimo/js-sdk/1.5.0/assets/logos/bnb-logo.png"
          - address: "0x64544969ed7EBf5f083679233325356EbE738930"
            name: "USDCoin"
            symbol: "USDC"
            decimals: 18
            logo_uri: "https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48/logo.png"
          - address: "0x337610d27c682E347C9cD60BD4b3b107C9d34dDd"
            name: "Tether USD"
            symbol: "USDT"
            decimals: 18
            logo_uri: "https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xdAC17F958D2ee523a2206206994597C13D831ec7/logo.png"
          - address: "0x29a751263Aa7fD3E7728F2A2c9136007A2d61Ac1"
            name: "USDC Rarimo"
            symbol: "USDC"
            decimals: 6
            logo_uri: "https://raw.githubusercontent.com/traderjoe-xyz/joe-tokenlists/main/logos/0xB6076C93701D6a07266c31066B298AeC6dd65c2d/logo.png"
